### ISSUE TITLE
integration test example does not work with certmanager v1.5.0

### ISSUE THREAD

**Issue by secustor** [cert-manager/webhook-example#32]
With v1.5.0 the test function `dns.SetBinariesPath()` has been removed and therefore the test example does not work anymore.     

I have tried to adapt the test, but I have failed so far.

**Comment by Dr-Shadow** [comment]
You can use the environnent variables to pass the path to etcd / kube-apiserver and kubectl binaries.

`TEST_ASSET_ETCD=./hack/bin/etcd TEST_ASSET_KUBE_APISERVER=./hack/bin/kube-apiserver TEST_ASSET_KUBECTL=./hack/bin/kubectl TEST_ZONE_NAME=<ZONE_NAME>. go test -v .`

**Comment by secustor** [comment]
@Dr-Shadow  Thx! This has helped me a lot!

**Comment by wallrj** [comment]
Fixed in #36 (I think)
