### ISSUE TITLE
Webhook CPU usage is rather high

### ISSUE THREAD

**Issue by aellwein** [cert-manager/webhook-example#43]
I occasionally look onto my k8s metrics (CPU/Mem Usage) and i found that the webhook server uses rather much CPU (up to 20 percent) over the time. 

From my understanding, a webhook server is a simple k8s OpenAPI server, an HTTP server, which should be actually sleeping most of the time, is this correct? So the CPU load in my expectation should be at most 5%.

in this case, i'm wondering what is causing that CPU load... 🤔

**Comment by fourstepper** [comment]
I think you are talking about the built-in cert-manager webhook, right? If so, this is not the right place to ask.

This repository contains an example "template" on how to implement and deploy your own custom webhook for DNS01 challenges.

Try the #cert-manager Slack channel on the Kubernetes Slack

**Comment by aellwein** [comment]
@fourstepper you are right, 
the webhook server is implemented in cert-manager, but in my opinion all custom webhook implementations derived 
from this repository (including [mine](https://github.com/aellwein/cert-manager-webhook-netcup)) are affected, because of [this line here](https://github.com/cert-manager/webhook-example/blob/97ebc9b1dd4f37f06642d7f34ffad5c3e6aae021/main.go#L28). Therefore i just wanted to leave it here, if someone else wonders about this behavior.
